scan_timeout = 100
command_timeout = 500

"$schema" = "https://starship.rs/config-schema.json"

follow_symlinks = false
palette = "kanagawa"

format = """
[\\[](bold overlay2)$hostname@$username[\\]](bold overlay2)\
$directory\
$git_branch\
$git_commit\
$git_status\
$python\
$status\
$jobs\
$aws\
$line_break\
$character"""

right_format = ""

[fill]
symbol = " "

[hostname]
ssh_only = false
format = "[$hostname](bold blue)"
disabled = false

[username]
show_always = true
format = "[$user](bold green)"

[directory]
truncation_length = 1
fish_style_pwd_dir_length = 1
format = " [$path](bold pink)$read_only "

[git_branch]
format = "[$branch](mauve) "
ignore_branches = ["HEAD"]

[git_commit]
only_detached = true
format = "[$hash$tag](mauve) "
tag_disabled = false
tag_symbol = ""

[git_status]
format = '($staged$modified$untracked$deleted$renamed$stashed$ahead_behind)'
staged = "[+${count} ](green)"
modified = "[!${count} ](yellow)"
untracked = "[?${count} ](blue)"
deleted = "[✘${count} ](red)"
renamed = "[»${count} ](mauve)"
stashed = '[$$${count} ](peach)'
ahead = "[⇡${count} ](yellow)"
behind = "[⇣${count} ](yellow)"
diverged = "[⇡${ahead_count}⇣${behind_count} ](red)"

[status]
disabled = false
format = "[\\[$status\\]](bold red) "

[character]
success_symbol = "[❯](bold green)"
error_symbol = "[❯](bold red)"
vimcmd_symbol = "[:](bold yellow)"
vimcmd_replace_one_symbol = "[:](bold mauve)"
vimcmd_replace_symbol = "[:](bold mauve)"

[package]
disabled = true

[docker_context]
disabled = true

[aws]
disabled = true
symbol = ""
format = "[$profile ($region)](peach)"

[python]
disabled = false
format = "[$virtualenv](green) "
version_format = ""

[nodejs]
disabled = true

[golang]
disabled = true

[rust]
disabled = true

[jobs]
format = "[\\[$number\\]](peach) "
number_threshold = 1

[palettes.kanagawa]
overlay2 = "#8C8C8C"
blue = "#7E9CD8"
green = "#76946A"
pink = "#D27E99"
mauve = "#957FB8"
peach = "#FF9E3B"
red = "#C34043"
yellow = "#E6C384"
