[fill]
symbol = " "

[character]
format = '$symbol '

[line_break]
disabled = false

[directory]
truncation_length = 1
fish_style_pwd_dir_length = 1

[package]
disabled = true

[docker_context]
disabled = true

[python]
pyenv_version_name = true
pyenv_prefix = ""

[aws]
disabled = true
